version: '3.2'
services:
  deus-server:
    image: "alexeyeremin/deus-server"
    networks:
      - overlay
    ports:
     - "8157:8157"
  deus-worker-manager:
    image: "alexeyeremin/deus-worker-manager"
    volumes:
      - type: volume
        source: models_src
        target: /deus-models
        read_only: true
    networks:
      - overlay
  deus-models:
    image: "alexeyeremin/deus-models"
    volumes:
      - type: volume
        source: models_src
        target: /app
  couchdb:
    image: "apache/couchdb"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      - overlay
    ports:
     - "5988:5984" # Remove when using in prod
    volumes:
      - type: volume
        source: couchdb_data
        target: /opt/couchdb/data
        volume:
          nocopy: true

volumes:
  couchdb_data:
    external: true
  models_src:

networks:
  overlay: