apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deus-qr-lib
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - qr.alice.magellan2018.ru
    secretName: tls-secret
  rules:
  - host: qr.alice.magellan2018.ru
    http:
      paths:
      - path: /
        backend:
          serviceName: deus-qr-lib
          servicePort: 8159
