apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deus-server
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - api.alice.magellan2018.ru
    secretName: tls-secret
  rules:
  - host: api.alice.magellan2018.ru
    http:
      paths:
      - path: /
        backend:
          serviceName: deus-server
          servicePort: 8157
