apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phpmyadmin
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - phpmyadmin.alice.magellan2018.ru
    secretName: tls-secret
  rules:
  - host: phpmyadmin.alice.magellan2018.ru
    http:
      paths:
      - path: /
        backend:
          serviceName: phpmyadmin
          servicePort: 8024
