apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: couchdb-init
spec:
  selector:
    matchLabels:
      component: couchdb-init
  template:
    metadata:
      labels:
        component: couchdb-init
    spec:
      initContainers:
      - name: deus-models
        image: alexeyeremin/deus-models
        volumeMounts:
        - name: models-src
          mountPath: /app
      containers:
      - name: deus-couchdb-init
        image: alexeyeremin/deus-couchdb-init
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        volumeMounts:
        - name: models-src
          mountPath: /deus-models
      volumes:
      - name: models-src
        emptyDir: {}
