apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      component: couchdb
  template:
    metadata:
      labels:
        component: couchdb
    spec:
      containers:
      - image: apache/couchdb
        name: couchdb
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        ports:
        - containerPort: 5984
        readinessProbe:
          httpGet:
            path: /_up
            port: 5984
            httpHeaders:
          initialDelaySeconds: 3
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /_up
            port: 5984
            httpHeaders:
          initialDelaySeconds: 3
          periodSeconds: 20
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: couchdb-data
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-data
