apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: technopark
spec:
  selector:
    matchLabels:
      component: technopark
  template:
    metadata:
      labels:
        component: technopark
    spec:
      containers:
      - image: docker-registry.alice.magellan2018.ru/technopark
        imagePullPolicy: Always
        name: technopark
        env:
        - name: MAGELLAN_MYSQL_HOST
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: alice-secret
              key: user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alice-secret
              key: password              
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /mcc/dashboard
            port: 8888
          initialDelaySeconds: 3
          periodSeconds: 20
          timeoutSeconds: 10
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /mcc/dashboard
            port: 8888
          initialDelaySeconds: 3
          periodSeconds: 20
          timeoutSeconds: 10
          periodSeconds: 60
