apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb
    spec:
      containers:
      - image: apache/couchdb
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:5984/_up
        name: couchdb
        ports:
        - containerPort: 5984
        resources: {}
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: couchdb-data
      restartPolicy: Always
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-data
status: {}
