apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: deus-models
  name: deus-models
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: deus-models
    spec:
      containers:
      - image: alexeyeremin/deus-models
        name: deus-models
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: models-src
      restartPolicy: Always
      volumes:
      - name: models-src
        persistentVolumeClaim:
          claimName: models-src
status: {}
