apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: medicine-frontend
  name: medicine-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: medicine-frontend
    spec:
      containers:
      - image: alexeyeremin/medicine-frontend
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:80/
        name: medicine-frontend
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
