apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    run: docker-registry
spec:
  type: NodePort
  selector:
    run: docker-registry
  ports:
  - name: http
    port: 5000
    protocol: TCP