apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
      - name: kibana
        image: docker-registry.alice.magellan2018.ru/kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: 5601
          initialDelaySeconds: 3
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /status
            port: 5601
          initialDelaySeconds: 3
          periodSeconds: 20