apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
          # See https://github.com/docker-library/mysql/issues/186#issuecomment-320342277 for reasons
          subPath: db
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
