apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    run: phpmyadmin
spec:
  type: NodePort
  selector:
    run: phpmyadmin
  ports:
  - name: http
    port: 8024
    targetPort: 80
    protocol: TCP
